baseURL = 'https://phyiction.github.io'
copyright = '&#169; 2023 <a href="https://github.com/phyiction/">phyiction</a>. All Rights Reserved.'
languageCode = 'en-us'
title = 'yet another tech blog'
theme = 'lite' 

[params]
  description = """
  Ramblings about some projects I've been working on. #showyourwork
  """
  math = true
  postDateFormat = "02 Jan 2006"
  
  [params.social]
    github = "https://github.com/phyiction/"

[menu]
  [[menu.main]]
    name = "Categories"
    weight = 1
    url = "/categories/"
  [[menu.main]]
    name = "Posts"
    weight = 2    
    url = "/post/"
  [[menu.main]]
    name = "Projects"
    weight = 3    
    url = "/project/"
