baseURL = 'https://phyiction.github.io'
copyright = '&#169; 2023 <a href="https://github.com/phyiction/">phyiction</a>. All Rights Reserved.'
googleAnalytics = 'G-15637L07J3'
languageCode = 'en-us'
title = 'yet another tech blog'
theme = 'lite'

[menu]
  [[menu.main]]
    name = "Blog"
    weight = 1    
    url = "/post/"
  [[menu.main]]
    name = "Projects"
    weight = 2    
    url = "/project/"

[params]
  description = """
  Ramblings about some projects I've been working on. #showyourwork
  """
  math = true
  postDateFormat = "02 Jan 2006"
  
  [params.social]
    github = "https://github.com/phyiction/"

[permalinks]
  post = ':sections/:year/:month/:slug'
  project = ':sections/:year/:month/:slug'

[taxonomies]  
  tag = 'tags'
